# Generated by Django 3.1.2 on 2020-12-06 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=120)),
                ('rua', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('informacao_adicional', models.CharField(max_length=240)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_produto', models.ImageField(upload_to='')),
                ('imagem_descricao', models.CharField(max_length=480)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_total', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco')),
                ('itempedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itempedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=240)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=480)),
            ],
        ),
        migrations.DeleteModel(
            name='Ususario',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produto'),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produto'),
        ),
    ]
