# Generated by Django 3.1.3 on 2020-12-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20201212_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='itempedido',
            new_name='item_pedido',
        ),
    ]
